name:                iridescence
version:             0.1.0.0
github:              "ntruong/iridescence"
license:             BSD3
author:              "Nicholas Truong"
maintainer:          "me@n-truong.com"
copyright:           "2019 Nicholas Truong"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ntruong/iridescence#readme>

dependencies:
- base <= 5
- JuicyPixels

library:
  source-dirs: src

executables:
  iridescence:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iridescence

tests:
  iridescence-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iridescence
